<?php

namespace App\Mail\Agency;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Attachment;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

/**
 * Emails an agency document (quote/invoice) to the client with the PDF attached.
 * PDF bytes are generated by AgencyPdfGenerator and passed in (kept private so
 * they are not exposed to the view).
 */
class AgencyDocumentMail extends Mailable
{
    use Queueable;
    use SerializesModels;

    public function __construct(
        public string $documentType,
        public string $number,
        public string $clientName,
        public string $businessName,
        private string $pdfBytes,
        private string $pdfFilename,
    ) {
    }

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: "{$this->documentType} {$this->number} - {$this->businessName}",
        );
    }

    public function content(): Content
    {
        return new Content(view: 'mail.agency-document');
    }

    /**
     * @return array<int, Attachment>
     */
    public function attachments(): array
    {
        return [
            Attachment::fromData(fn (): string => $this->pdfBytes, $this->pdfFilename)
                ->withMime('application/pdf'),
        ];
    }
}
